---
- name: optionally unstack
  shell: PATH="/usr/sbin:$PATH" ./unstack.sh
  args:
    chdir: ~/devstack
  ignore_errors: yes

- name: build OpenStack via stack.sh
  command: ./stack.sh
  args:
    chdir: ~/devstack
