---
- name: Install pip
  become: yes
  yum:
    name: python-pip
    state: present

- name: Update python dependencies
  become: yes
  pip:
    name:
      - setuptools==43.0.0
      - requests
    state: forcereinstall

- name: optionally unstack
  shell: PATH="/usr/sbin:$PATH" ./unstack.sh
  args:
    chdir: ~/devstack
  ignore_errors: yes

- name: build OpenStack via stack.sh
  command: ./stack.sh
  args:
    chdir: ~/devstack
