- name: Install required utilities
  become: yes
  yum:
    name:
      - python-devel
      - epel-release
      - gcc
      - git
      - ansible-2.4.*
      - yum-utils
      - libffi-devel
    state: present

- name: Install pip
  become: yes
  yum:
    name: python-pip
    state: present

- name: Create directory for docker config
  become: yes
  file:
    path: /etc/docker/
    state: directory
  when: docker_config is defined and docker_config

- name: Create docker config
  become: yes
  copy:
    content: "{{ docker_config | to_nice_json }}"
    dest: /etc/docker/daemon.json
  when: docker_config is defined and docker_config

- name: Add docker-ce repository
  become: yes
  shell: |
    yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: Install docker
  become: yes
  yum:
    name: docker-ce
    state: present

- name: Start docker daemon
  become: yes
  service:
    name: docker
    state: started
    enabled: yes

- name: Add user to docker group
  become: yes
  user:
    name: centos
    groups: docker
    append: yes

- name: install docker and docker-compose for python
  pip:
    name:
      - docker-py==1.10.6
      - docker-compose==1.9.0
    state: present
    extra_args: --user