- hosts: controller
  tasks:
    # This ansible is a workaround for devstack error with installing
    # uwsgi on CentOS with stable/queens or stable/train branch.
    # This should be removed as soon as the change
    # https://review.opendev.org/#/c/736189/ is merged or any other
    # fix is applied to openstack/devstack.
    - name: Update Apache file from devstack repository
      become: yes
      copy:
        remote_src: yes
        src: /home/zuul/src/opendev.org/x/networking-opencontrail/fixed_apache_script
        dest: /opt/stack/devstack/lib/apache

- hosts: controller
  roles:
    - run-devstack
    - run-contrail
  tasks:
    - name: Install ius-release
      become: yes
      yum:
        name: https://repo.ius.io/ius-release-el7.rpm
        state: present
        update_cache: yes

    - name: Install ius-release 2
      become: yes
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present
        update_cache: yes

    - name: Install Python3.6
      become: yes
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - python36u
        - python36u-devel
        - python36u-pip
        - python36u-setuptools

    - name: Create symlink on Python3
      # Python36 installation don't create Python3 symlink which is used by tox.
      become: yes
      file:
        src: /usr/bin/python3.6
        dest: /usr/bin/python3
        state: link

    # This workaround allows to replace opencontrail-router service plugin
    # with proper L3RouterPlugin. After fixing opencontrail-router alias
    # this task should be removed along with the script file.
    - name: Add L3 Neutron configuration to configuration
      script: add_router_to_neutron_conf.py
      become: yes

    - name: Restart neutron-server
      service:
        name: devstack@q-svc
        state: restarted
      become: yes

    - name: Wait for Neutron to wake up
      shell: source /opt/stack/devstack/userrc_early && openstack network list
      args:
        chdir: "{{ zuul.project.src_dir }}"
        executable: /bin/bash
      retries: 20
      delay: 10
      register: result
      until: result.rc == 0

    - name: Execute noc-integration tests
      shell: |
        export CONTRAIL_IP={{ hostvars['controller'].ansible_default_ipv4.address }}
        stestr -c networking_opencontrail/tests/integration/.stestr.conf run --concurrency=1
      become: yes
      args:
        chdir: "{{ zuul.project.src_dir }}"
        executable: /bin/bash
