---
- name: Get vrouter docker name
  become: yes
  shell: |
    docker ps --filter "label=net.juniper.contrail.container.name=contrail-vrouter-agent" --format {{' "{{.Names}}" '}}
  changed_when: false
  check_mode: no
  register: vrouter_docker_name

- name: Copy vrouter-port-control
  become: yes
  shell: |
    docker cp {{ vrouter_docker_name.stdout }}:/usr/bin/vrouter-port-control /usr/bin/

- name: Install contrail-nova-vif-driver
  become: yes
  shell: |
    pip install openstacksdk==0.36.0 docker-compose==1.9.0 dogpile.cache==0.7.1 pyasn1-modules==0.2.6 networkx==2.2 requests==2.22 decorator==4.4.0 PyYAML==3.10 ipaddress==1.0.16 more-itertools==5.0.0 numpy==1.16.5 git+https://github.com/Juniper/contrail-controller.git#subdirectory=src/vnsw/contrail-vrouter-api/ git+https://github.com/Juniper/contrail-nova-vif-driver.git