#!/usr/bin/env ansible-playbook

- hosts: controller
  roles:
    - devstack_node
    - config_controller_node
    - restack_node

- hosts: contrail_controller
  roles:
    - contrail_node

- hosts: controller
  roles:
    - { role: networking_bgpvpn_plugin, when: install_networking_bgpvpn_plugin }
    - { role: restack_node, when: install_networking_bgpvpn_plugin }

- hosts: compute
  roles:
  - role: devstack_node
  - role: config_compute_node
  - role: restack_node

- hosts: controller
  roles:
    - discover_computes
