---
- name: Install required utilities
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - lvm2
    - git
    - python
    - epel-release

- name: Install pip
  become: yes
  yum:
    name: python-pip
    state: present

- name: Update setuptools
  become: yes
  shell: pip install --upgrade setuptools

- name: Fetch devstack
  git:
    repo: "https://github.com/openstack-dev/devstack.git"
    dest: ~/devstack
    version: "{{ openstack_branch }}"
    accept_hostkey: yes
    force: yes

- name: Put local.conf
  template:
    src: compute_local.conf.j2
    dest: ~/devstack/local.conf
