---
# Run stack.sh in case if it is already running, unstack first

- name: optionally unstack
  shell: screen -ls | grep stack && ./unstack.sh
  args:
    chdir: ~/devstack
  ignore_errors: yes

- name: stack.sh again Contrail
  shell: ./stack.sh
  args:
    chdir: ~/devstack
  ignore_errors: no
